#!/usr/bin/env node

(function () {
    "use strict";
    
    var coveraje = require("coveraje").coveraje,
        fs = require("fs"),
        path = require("path");
    var filePath = path.resolve(path.join(__dirname, "../jshint.js"));
        
    function runTests(file, helper) {
        return function (context) {
            // hack: set cache value
            require.cache[filePath] = {
                id: filePath,
                exports: context.exports,
                loaded: true
            };
            
            return coveraje.runHelper(helper).run(file);
        };
    }
    
    var tests = {};
    
    fs.readdir(__dirname, function (err, files) {
        files.forEach(function (f) {
            if (f.length > 2 && f.substr(f.length - 3, 3) === ".js" && f.substr(0, 1) !== ".") {
                tests[f] = runTests(path.join(__dirname, f), "expresso");
            }
        });
        
        coveraje.cover(
            function () {
                // always read the content from disk, so changes can be refreshed in the browser
                try {
                    return fs.readFileSync(filePath, 'utf-8');
                } catch (ex) {
                    return "{ /*" + ex.message + "*/ }";
                }
            },
            tests,
            {
                useServer: true,
                globals: "node"
            }
        );
    });
}());
